Updated rbac and demonset example bloc
The rbac and demonset deployment bloc are out of date with the linked yaml files.

In particular, if you try to copy those blocs and deploy with "kubectl apply -f local_file" you'll fail with

error: error validating "traefik-ds.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false

as the "selector" fields are required in v1 of the API.