Update kubernetes-crd.md
The contents of the IngressRoute tab have whitespace errors. When you copy that and paste it into a file you get the following error:

ingressroute.traefik.containo.us/myingressroute created
error: error parsing traefik-4.yaml: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context

This change corrects the format for that file so that it properly creates the ingress routes:

deployment.apps/whoami created
service/whoami created
deployment.apps/whoamitcp created
service/whoamitcp created
deployment.apps/whoamiudp created
service/whoamiudp created